### ISSUE TITLE
Specify the operand data type constraints of operation

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#283]
The current spec doesn't specify the operand type constraints of an operation. However, some operations, e.g., [`softmax`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-softmax) should only support float32 operand type according to the survey of frameworks and native ML APIs in the following table. The lack of the operand type constraints specification would lead to implementation issue, such as [Chromium CL 3856752](https://chromium-review.googlesource.com/c/chromium/src/+/3856752/comments/267c926c_b14af87f).

| Framework / API | supported data types |
|---|---|
| TensorFlow [tf.nn.softmax](https://www.tensorflow.org/api_docs/python/tf/nn/softmax) | half, float32, float64 |
| ONNX [Softmax](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Softmax) | tensor(float16), tensor(float), tensor(double), tensor(bfloat16) |
| NNAPI [ANEURALNETWORKS_SOFTMAX](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a2bfbb83a537701e2843a3d5004250c2c) | FLOAT32, FLOAT16 |
| DirectML [DML_ACTIVATION_SOFTMAX_OPERATOR_DESC](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_activation_softmax_operator_desc) | FLOAT32, FLOAT16 |
| BNNS [ActivationFunction](https://developer.apple.com/documentation/accelerate/bnns/activationlayer/3649741-init) | float |

Thanks @wacky6 for pointing this out.

**Comment by huningxin** [comment]
There are other operations should constrain the operand to floating-point types, e.g., [batchNormalization](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-batchnorm), [elu](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-elu), [hardSigmoid](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-hard-sigmoid), [hardSwish](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-hard-swish), [instanceNormalization](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-instancenorm), [leakyRelu](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-leakyrelu), [linear](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-linear), [sigmoid](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-sigmoid), [softplus](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-softplus), [softsign](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-softsign), [tanh](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-tanh).

**Comment by huningxin** [comment]
Also for `prelu` op as raised by @wacky6 in the Chromium [CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4396686/comment/6f0d7438_719bbcf5/). Thanks again Jiewei!

**Comment by huningxin** [comment]
For some [element-wise unary ops](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-unary), `ceil` and `floor` should only accept floating-point types. `neg` should only accept signed types, including signed integer and floating-point types. This feedback is from Chromium [CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4408709/comment/f2ccfcc3_e9347ced/). Thanks @wacky6 and @miaobin!

**Comment by huningxin** [comment]
(Feedback raised by @wacky6 from Chromium [CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4957470/comment/a9df5732_f90817b8/))

For [reduction ops](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-reduce), `reduceL2`, `reduceLogSum`, `reduceLogSumExp` and `reduceMean` should only accept floating-point types.

/cc @lisa0314 @fdwr

**Comment by fdwr** [comment]
> reduceL2, reduceLogSum, reduceLogSumExp and reduceMean should only accept floating-point types.

That's consistent with DML's data type support too:

```
REDUCE:
  ARGMIN, ARGMAX:
    featureLevel: 4.1
    InputDataType:  uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    OutputDataType: uint32, uint64, int32, int64
    MinRank: 1
    MaxRank: 8
  AVERAGE, L2, LOG_SUM, LOG_SUM_EXP:
    featureLevel: 3.0
    InputDataType:  float16, float32
    OutputDataType: float16, float32
    MinRank: 1
    MaxRank: 8
  L1, SUM_SQUARE:
    featureLevel: 5.0
    InputDataType:  uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    OutputDataType: uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    MinRank: 1
    MaxRank: 8
  MIN, MaxRank:
    featureLevel: 5.0
    InputDataType:  uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    OutputDataType: uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    MinRank: 1
    MaxRank: 8
  MULTIPLY, SUM:
    featureLevel: 5.0
    InputDataType:  uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    OutputDataType: uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32
    MinRank: 1
    MaxRank: 8
```
